version: '3'

services:
  app:
    container_name: node-docker-setup
    restart: always
    build: .
    ports:
      - '80:8082'
    links:
      - mongo
  
  mongo:
    container_name: node-docker-mongo
    image: mongo
    ports:
      - '27017:27017'